version: 2.1

jobs:
  deploy:
    parameters:
      environment_name:
        type: string
      component_name:
        type: string
      target_version:
        type: string
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: ""
          command: |
            circleci run release log \
              --environment-name=<< parameters.environment_name >> \
              --component-name=<< parameters.component_name >> \
              --target-version=<< parameters.target_version >>

workflows:
  release-A:
    jobs:
      - deploy:
          environment_name: "production"
          component_name: "A"
          target_version: $CIRCLE_BUILD_NUM
  release-B:
    jobs:
      - deploy:
          environment_name: "production"
          component_name: "B"
          target_version: $CIRCLE_BUILD_NUM
  staging-B:
    jobs:
      - deploy:
          environment_name: "staging"
          component_name: "B"
          target_version: $CIRCLE_BUILD_NUM
